### ISSUE TITLE
Maximum call stack exceeded error 

### ISSUE THREAD

**Issue by whitecolor** [danielmoore/ts-babel-node#2]
tried to replace `ts-babel` with `ts-babel-node`
```js
require('babel-core/register')
require('ts-babel-node/register') // was ts-node
```

```
RangeError: Maximum call stack size exceeded
    at Object.stringify (native)
    at process.target._send (internal/child_process.js:586:23)
    at process.target.send (internal/child_process.js:507:19)
    at Object.exports.send (...\node_modules\node-dev\lib\ipc.js:14:23)
    at ...\node_modules\node-dev\lib\wrap.js:54:7
    at nodeDevHook (...\node_modules\node-dev\lib\hook.js:53:27)
    at mockLoad (...\node_modules\ts-babel-node\index.js:83:3)
    at compile (...\node_modules\ts-babel-node\index.js:66:18)
    at loadPipeline (...\node_modules\ts-babel-node\index.js:62:14)
    at nodeDevHook (...\node_modules\node-dev\lib\hook.js:56:7)
    at mockLoad (...\node_modules\ts-babel-node\index.js:83:3)
    at compile (...\node_modules\ts-babel-node\index.js:66:18)
    at loadPipeline (...\node_modules\ts-babel-node\index.js:62:14)
    at nodeDevHook (...\node_modules\node-dev\lib\hook.js:56:7)
    at mockLoad (...\node_modules\ts-babel-node\index.js:83:3)
    at compile (...\node_modules\ts-babel-node\index.js:66:18)
    at loadPipeline (...\node_modules\ts-babel-node\index.js:62:14)
    at nodeDevHook (...\node_modules\node-dev\lib\hook.js:56:7)
    at mockLoad (...\node_modules\ts-babel-node\index.js:83:3)
    at compile (...\node_modules\ts-babel-node\index.js:66:18)
    at loadPipeline (...\node_modules\ts-babel-node\index.js:62:14)
    at nodeDevHook (...\node_modules\node-dev\lib\hook.js:56:7)
```

what can be the reason?

**Comment by danielmoore** [comment]
You shouldn't need to call `require('babel-core/register')`. ts-babel-node will take care of that for you :)
